# fly.toml app configuration file generated for job-hunting on 2026-07-12T21:43:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-hunting'
primary_region = 'yyz'

[build]

[env]
  DB_FILE_NAME = "/data/jobs.db"
  OPENAI_MODEL_DEFAULT="gpt-5-mini"
  OPENAI_MODEL_JOB_PARSER="gpt-5-mini"
  OPENAI_MODEL_RESUME="gpt-5.5"
  OPENAI_MODEL_COVER_LETTER="gpt-5.4-mini"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
